<?php
$lang="en_US.UTF-8";
$htpassword_cmd="/usr/local/apache2/bin/htpasswd";
$svn_cmd="/usr/local/bin/svn";
$svnadmin_cmd="/usr/local/bin/svnadmin";
$svn_config_dir="/data/svn/svnroot";
$svn_repos_loc="/data/svn/svnroot";
$svn_passwd_file="/data/svn/passwdfile";
$svn_access_file="/data/svn/accessfile";
$svn_trash_loc="";
$svnserve_user_file="";
$smtp_server="smtp.mailserver.net";
$dsn="mysql_uri";
$admin_name="admin";
$admin_temp_password="admin";
?>